In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0, 100, (10, 2))

In [4]:
data

array([[35, 14],
       [66, 97],
       [ 4, 86],
       [99, 13],
       [52,  2],
       [32, 28],
       [15, 47],
       [12, 40],
       [39, 60],
       [70, 91]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.32631579, 0.12631579],
       [0.65263158, 1.        ],
       [0.        , 0.88421053],
       [1.        , 0.11578947],
       [0.50526316, 0.        ],
       [0.29473684, 0.27368421],
       [0.11578947, 0.47368421],
       [0.08421053, 0.4       ],
       [0.36842105, 0.61052632],
       [0.69473684, 0.93684211]])

In [9]:
scaler_model.fit_transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.32631579, 0.12631579],
       [0.65263158, 1.        ],
       [0.        , 0.88421053],
       [1.        , 0.11578947],
       [0.50526316, 0.        ],
       [0.29473684, 0.27368421],
       [0.11578947, 0.47368421],
       [0.08421053, 0.4       ],
       [0.36842105, 0.61052632],
       [0.69473684, 0.93684211]])

In [10]:
import pandas as pd

In [11]:
dt = np.random.randint(0, 101, (50, 4))

In [12]:
dt

array([[15, 30, 44, 28],
       [75, 66, 45, 21],
       [65, 69, 10, 57],
       [12, 27, 22, 76],
       [94, 80, 96, 78],
       [ 7, 87, 29, 76],
       [98, 85, 89, 69],
       [36, 64, 54, 31],
       [ 6, 40, 37, 26],
       [74, 60, 89, 63],
       [22, 66, 98, 16],
       [32, 64, 81, 86],
       [22, 99, 43, 27],
       [28, 66, 77,  7],
       [68, 84, 99, 49],
       [99, 27, 63, 42],
       [95,  4, 73, 15],
       [66, 69,  6, 78],
       [15, 83, 23, 99],
       [31, 17, 53,  9],
       [43, 79, 59, 94],
       [57, 69, 75, 88],
       [92, 81, 92, 61],
       [74, 24, 83, 19],
       [86, 40, 35, 84],
       [65, 55, 86, 73],
       [ 6, 77, 45, 32],
       [83, 10, 56,  5],
       [50, 68, 49, 31],
       [17, 30, 29, 76],
       [84, 22, 51, 12],
       [ 2, 41,  3, 99],
       [51, 39, 90, 38],
       [56, 67, 22, 30],
       [91, 56, 70, 54],
       [ 5, 26, 32, 27],
       [42, 23, 85, 71],
       [22, 67, 42, 10],
       [15,  7, 59, 46],
       [79, 83, 15, 62],


In [13]:
df = pd.DataFrame(data = dt)

In [14]:
df

0   1   2   3
0   15  30  44  28
1   75  66  45  21
2   65  69  10  57
3   12  27  22  76
4   94  80  96  78
5    7  87  29  76
6   98  85  89  69
7   36  64  54  31
8    6  40  37  26
9   74  60  89  63
10  22  66  98  16
11  32  64  81  86
12  22  99  43  27
13  28  66  77   7
14  68  84  99  49
15  99  27  63  42
16  95   4  73  15
17  66  69   6  78
18  15  83  23  99
19  31  17  53   9
20  43  79  59  94
21  57  69  75  88
22  92  81  92  61
23  74  24  83  19
24  86  40  35  84
25  65  55  86  73
26   6  77  45  32
27  83  10  56   5
28  50  68  49  31
29  17  30  29  76
30  84  22  51  12
31   2  41   3  99
32  51  39  90  38
33  56  67  22  30
34  91  56  70  54
35   5  26  32  27
36  42  23  85  71
37  22  67  42  10
38  15   7  59  46
39  79  83  15  62
40  46  58  30  39
41  80  12  83  96
42  13  26  58  76
43  70  47  45  68
44  95  76  14  25
45  82   7  19  61
46  42  58  73  29
47  25  36  34  26
48  80  53  27  55
49  85  83  96  98

In [15]:
df = pd.DataFrame(data = dt, columns = ['C1', 'C2', 'C3', 'C4'])

In [16]:
df

C1  C2  C3  C4
0   15  30  44  28
1   75  66  45  21
2   65  69  10  57
3   12  27  22  76
4   94  80  96  78
5    7  87  29  76
6   98  85  89  69
7   36  64  54  31
8    6  40  37  26
9   74  60  89  63
10  22  66  98  16
11  32  64  81  86
12  22  99  43  27
13  28  66  77   7
14  68  84  99  49
15  99  27  63  42
16  95   4  73  15
17  66  69   6  78
18  15  83  23  99
19  31  17  53   9
20  43  79  59  94
21  57  69  75  88
22  92  81  92  61
23  74  24  83  19
24  86  40  35  84
25  65  55  86  73
26   6  77  45  32
27  83  10  56   5
28  50  68  49  31
29  17  30  29  76
30  84  22  51  12
31   2  41   3  99
32  51  39  90  38
33  56  67  22  30
34  91  56  70  54
35   5  26  32  27
36  42  23  85  71
37  22  67  42  10
38  15   7  59  46
39  79  83  15  62
40  46  58  30  39
41  80  12  83  96
42  13  26  58  76
43  70  47  45  68
44  95  76  14  25
45  82   7  19  61
46  42  58  73  29
47  25  36  34  26
48  80  53  27  55
49  85  83  96  98

In [17]:
x = df[['C1', 'C2', 'C3']]

In [18]:
y = df['C4']

In [19]:
x

C1  C2  C3
0   15  30  44
1   75  66  45
2   65  69  10
3   12  27  22
4   94  80  96
5    7  87  29
6   98  85  89
7   36  64  54
8    6  40  37
9   74  60  89
10  22  66  98
11  32  64  81
12  22  99  43
13  28  66  77
14  68  84  99
15  99  27  63
16  95   4  73
17  66  69   6
18  15  83  23
19  31  17  53
20  43  79  59
21  57  69  75
22  92  81  92
23  74  24  83
24  86  40  35
25  65  55  86
26   6  77  45
27  83  10  56
28  50  68  49
29  17  30  29
30  84  22  51
31   2  41   3
32  51  39  90
33  56  67  22
34  91  56  70
35   5  26  32
36  42  23  85
37  22  67  42
38  15   7  59
39  79  83  15
40  46  58  30
41  80  12  83
42  13  26  58
43  70  47  45
44  95  76  14
45  82   7  19
46  42  58  73
47  25  36  34
48  80  53  27
49  85  83  96

In [20]:
y

0     28
1     21
2     57
3     76
4     78
5     76
6     69
7     31
8     26
9     63
10    16
11    86
12    27
13     7
14    49
15    42
16    15
17    78
18    99
19     9
20    94
21    88
22    61
23    19
24    84
25    73
26    32
27     5
28    31
29    76
30    12
31    99
32    38
33    30
34    54
35    27
36    71
37    10
38    46
39    62
40    39
41    96
42    76
43    68
44    25
45    61
46    29
47    26
48    55
49    98
Name: C4, dtype: int32

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [23]:
X_train.shape

(33, 3)

In [24]:
X_test.shape

(17, 3)

In [25]:
y_train.shape

(33,)

In [26]:
y_test.shape

(17,)